[functions]
  verify_jwt = true

[functions.focusnfe-webhook]
  verify_jwt = false

[functions.woocommerce-webhook]
  verify_jwt = false

[functions.woocommerce-worker]
  verify_jwt = false

[functions.woocommerce-scheduler]
  verify_jwt = false

[functions.inter-webhook]
  verify_jwt = false

[functions.meli-webhook]
  verify_jwt = false

[functions.meli-worker]
  verify_jwt = false

[functions.meli-scheduler]
  verify_jwt = false

[functions.shopee-webhook]
  verify_jwt = false

[functions.shopee-worker]
  verify_jwt = false

[functions.shopee-scheduler]
  verify_jwt = false

[functions.manual-create-user]
  cors_origins = ["http://localhost:5173"]
  cors_methods = ["POST", "OPTIONS"]
  cors_headers = ["authorization", "content-type"]
