export type FiscalCountryCode = {
  codigo: string; // cPais (NFe) com 4 dígitos
  nome: string; // nome em PT-BR (maiúsculo, conforme tabela)
};

// Lista de países para o campo fiscal `cPais` (NFe) usado em `pais_codigo`.
// Fonte (tabela pública): FazComex – Código de Países (NFe x Siscomex).
// Importante: manter `codigo` com 4 dígitos (incluindo zeros à esquerda).
export const FISCAL_COUNTRY_CODES: readonly FiscalCountryCode[] = [
  { nome: 'AFEGANISTAO', codigo: '0132' },
  { nome: 'AFRICA DO SUL', codigo: '0756' },
  { nome: 'ALBANIA', codigo: '0175' },
  { nome: 'ALEMANHA', codigo: '0230' },
  { nome: 'ANDORRA', codigo: '0370' },
  { nome: 'ANGOLA', codigo: '0400' },
  { nome: 'ANGUILLA', codigo: '0418' },
  { nome: 'ANTARTICA', codigo: '0420' },
  { nome: 'ANTIGUA E BARBUDA', codigo: '0434' },
  { nome: 'ANTILHAS HOLANDESAS', codigo: '0477' },
  { nome: 'ARABIA SAUDITA', codigo: '0531' },
  { nome: 'ARGELIA', codigo: '0590' },
  { nome: 'ARGENTINA', codigo: '0639' },
  { nome: 'ARMENIA', codigo: '0647' },
  { nome: 'ARUBA', codigo: '0655' },
  { nome: 'AUSTRALIA', codigo: '0698' },
  { nome: 'AUSTRIA', codigo: '0728' },
  { nome: 'AZERBAIJAO', codigo: '0736' },
  { nome: 'BAHAMAS', codigo: '0779' },
  { nome: 'BAHREIN', codigo: '0809' },
  { nome: 'BANGLADESH', codigo: '0817' },
  { nome: 'BARBADOS', codigo: '0833' },
  { nome: 'BELARUS', codigo: '0850' },
  { nome: 'BELGICA', codigo: '0876' },
  { nome: 'BELIZE', codigo: '0884' },
  { nome: 'BERMUDAS', codigo: '0906' },
  { nome: 'BOLIVIA', codigo: '0973' },
  { nome: 'BOSNIA-HERZEGOVINA', codigo: '0981' },
  { nome: 'BOTSUANA', codigo: '1015' },
  { nome: 'BRASIL', codigo: '1058' },
  { nome: 'BRUNEI', codigo: '1082' },
  { nome: 'BULGARIA', codigo: '1112' },
  { nome: 'BURKINA FASO', codigo: '0310' },
  { nome: 'BURUNDI', codigo: '1155' },
  { nome: 'BUTAO', codigo: '1198' },
  { nome: 'CABO VERDE', codigo: '1279' },
  { nome: 'CAMAROES', codigo: '1457' },
  { nome: 'CAMBOJA', codigo: '1414' },
  { nome: 'CANADA', codigo: '1490' },
  { nome: 'CAZAQUISTAO', codigo: '1538' },
  { nome: 'CATAR', codigo: '1546' },
  { nome: 'CHILE', codigo: '1589' },
  { nome: 'CHINA', codigo: '1600' },
  { nome: 'CHIPRE', codigo: '1635' },
  { nome: 'CINGAPURA', codigo: '1651' },
  { nome: 'COLOMBIA', codigo: '1694' },
  { nome: 'COMORES', codigo: '1732' },
  { nome: 'CONGO', codigo: '1775' },
  { nome: 'COREIA DO NORTE', codigo: '1872' },
  { nome: 'COREIA DO SUL', codigo: '1902' },
  { nome: 'COSTA DO MARFIM', codigo: '1937' },
  { nome: 'COSTA RICA', codigo: '1961' },
  { nome: 'CROACIA', codigo: '1953' },
  { nome: 'CUBA', codigo: '1996' },
  { nome: 'CURACAO', codigo: '0200' },
  { nome: 'DINAMARCA', codigo: '2321' },
  { nome: 'DJIBUTI', codigo: '7838' },
  { nome: 'DOMINICA', codigo: '2356' },
  { nome: 'EGITO', codigo: '2402' },
  { nome: 'EL SALVADOR', codigo: '6874' },
  { nome: 'EMIRADOS ARABES UNIDOS', codigo: '2445' },
  { nome: 'EQUADOR', codigo: '2399' },
  { nome: 'ERITREIA', codigo: '2437' },
  { nome: 'ESLOVAQUIA', codigo: '2470' },
  { nome: 'ESLOVENIA', codigo: '2461' },
  { nome: 'ESPANHA', codigo: '2453' },
  { nome: 'ESTADOS UNIDOS', codigo: '2496' },
  { nome: 'ESTONIA', codigo: '2518' },
  { nome: 'ETIOPIA', codigo: '2534' },
  { nome: 'FALKLAND (ILHAS MALVINAS)', codigo: '2550' },
  { nome: 'FEROE', codigo: '2593' },
  { nome: 'FIJI', codigo: '8702' },
  { nome: 'FILIPINAS', codigo: '2674' },
  { nome: 'FINLANDIA', codigo: '2712' },
  { nome: 'FRANCA', codigo: '2755' },
  { nome: 'GABAO', codigo: '2810' },
  { nome: 'GAMBIA', codigo: '2852' },
  { nome: 'GANA', codigo: '2895' },
  { nome: 'GEORGIA', codigo: '2917' },
  { nome: 'GIBRALTAR', codigo: '2933' },
  { nome: 'GRANADA', codigo: '2976' },
  { nome: 'GRECIA', codigo: '3018' },
  { nome: 'GROENLANDIA', codigo: '3050' },
  { nome: 'GUADALUPE', codigo: '3093' },
  { nome: 'GUAM', codigo: '3131' },
  { nome: 'GUATEMALA', codigo: '3174' },
  { nome: 'GUIANA', codigo: '3379' },
  { nome: 'GUIANA FRANCESA', codigo: '3255' },
  { nome: 'GUINE', codigo: '3298' },
  { nome: 'GUINE-EQUATORIAL', codigo: '3310' },
  { nome: 'GUINE-BISSAU', codigo: '3344' },
  { nome: 'HAITI', codigo: '3417' },
  { nome: 'HOLANDA (PAISES BAIXOS)', codigo: '5738' },
  { nome: 'HONDURAS', codigo: '3450' },
  { nome: 'HONG KONG', codigo: '3514' },
  { nome: 'HUNGRIA', codigo: '3557' },
  { nome: 'IEMEN', codigo: '3573' },
  { nome: 'ILHAS CAYMAN', codigo: '1376' },
  { nome: 'ILHAS CHRISTMAS', codigo: '3595' },
  { nome: 'ILHAS COCOS (KEELING)', codigo: '3607' },
  { nome: 'ILHAS COOK', codigo: '3615' },
  { nome: 'ILHAS DE MAN', codigo: '3690' },
  { nome: 'ILHAS MARIANAS', codigo: '4723' },
  { nome: 'ILHAS MARSHALL', codigo: '4731' },
  { nome: 'ILHAS PITCAIRN', codigo: '5933' },
  { nome: 'ILHAS SALOMAO', codigo: '6777' },
  { nome: 'ILHAS TURKS E CAICOS', codigo: '8230' },
  { nome: 'ILHAS VIRGENS (BRITANICAS)', codigo: '8638' },
  { nome: 'ILHAS VIRGENS (EUA)', codigo: '8662' },
  { nome: 'INDIA', codigo: '3619' },
  { nome: 'INDONESIA', codigo: '3651' },
  { nome: 'IRA', codigo: '3724' },
  { nome: 'IRAQUE', codigo: '3694' },
  { nome: 'IRLANDA', codigo: '3759' },
  { nome: 'ISLANDIA', codigo: '3791' },
  { nome: 'ISRAEL', codigo: '3830' },
  { nome: 'ITALIA', codigo: '3864' },
  { nome: 'JAMAICA', codigo: '3910' },
  { nome: 'JAPAO', codigo: '3999' },
  { nome: 'JERSEY', codigo: '3937' },
  { nome: 'JORDANIA', codigo: '4030' },
  { nome: 'KIRIBATI', codigo: '4111' },
  { nome: 'KUWAIT', codigo: '1988' },
  { nome: 'LAOS', codigo: '4200' },
  { nome: 'LESOTO', codigo: '4260' },
  { nome: 'LETONIA', codigo: '4278' },
  { nome: 'LIBANO', codigo: '4316' },
  { nome: 'LIBERIA', codigo: '4340' },
  { nome: 'LIBIA', codigo: '4383' },
  { nome: 'LIECHTENSTEIN', codigo: '4405' },
  { nome: 'LITUANIA', codigo: '4421' },
  { nome: 'LUXEMBURGO', codigo: '4456' },
  { nome: 'MACAU', codigo: '4472' },
  { nome: 'MACEDONIA', codigo: '4499' },
  { nome: 'MADAGASCAR', codigo: '4502' },
  { nome: 'MALASIA', codigo: '4553' },
  { nome: 'MALAVI', codigo: '4588' },
  { nome: 'MALDIVAS', codigo: '4618' },
  { nome: 'MALI', codigo: '4642' },
  { nome: 'MALTA', codigo: '4677' },
  { nome: 'MARROCOS', codigo: '4740' },
  { nome: 'MARTINICA', codigo: '4774' },
  { nome: 'MAURICIO', codigo: '4855' },
  { nome: 'MAURITANIA', codigo: '4880' },
  { nome: 'MAYOTTE', codigo: '4928' },
  { nome: 'MEXICO', codigo: '4936' },
  { nome: 'MIANMAR (BIRMANIA)', codigo: '0930' },
  { nome: 'MICRONESIA', codigo: '4995' },
  { nome: 'MOCAMBIQUE', codigo: '5053' },
  { nome: 'MOLDAVIA', codigo: '4944' },
  { nome: 'MONACO', codigo: '4952' },
  { nome: 'MONGOLIA', codigo: '4979' },
  { nome: 'MONTENEGRO', codigo: '4985' },
  { nome: 'MONTSERRAT', codigo: '5010' },
  { nome: 'NAMIBIA', codigo: '5070' },
  { nome: 'NAURU', codigo: '5088' },
  { nome: 'NEPAL', codigo: '5177' },
  { nome: 'NICARAGUA', codigo: '5215' },
  { nome: 'NIGER', codigo: '5258' },
  { nome: 'NIGERIA', codigo: '5282' },
  { nome: 'NIUE', codigo: '5312' },
  { nome: 'NORUEGA', codigo: '5380' },
  { nome: 'NOVA CALEDONIA', codigo: '5428' },
  { nome: 'NOVA ZELANDIA', codigo: '5487' },
  { nome: 'OMA', codigo: '5568' },
  { nome: 'PAISES BAIXOS (HOLANDA)', codigo: '5738' },
  { nome: 'PALAU', codigo: '5754' },
  { nome: 'PANAMA', codigo: '5800' },
  { nome: 'PAPUA NOVA GUINE', codigo: '5452' },
  { nome: 'PAQUISTAO', codigo: '5762' },
  { nome: 'PARAGUAI', codigo: '5860' },
  { nome: 'PERU', codigo: '5894' },
  { nome: 'POLINESIA FRANCESA', codigo: '5991' },
  { nome: 'POLONIA', codigo: '6033' },
  { nome: 'PORTO RICO', codigo: '6114' },
  { nome: 'PORTUGAL', codigo: '6076' },
  { nome: 'QUENIA', codigo: '6238' },
  { nome: 'QUIRGUIZ', codigo: '6254' },
  { nome: 'REINO UNIDO', codigo: '6289' },
  { nome: 'REPUBLICA CENTRO AFRICANA', codigo: '6408' },
  { nome: 'REPUBLICA DOMINICANA', codigo: '6475' },
  { nome: 'REPUBLICA TCHECA', codigo: '7919' },
  { nome: 'ROMENIA', codigo: '6700' },
  { nome: 'RUANDA', codigo: '6759' },
  { nome: 'RUSSIA', codigo: '6767' },
  { nome: 'SAARA OCIDENTAL', codigo: '6858' },
  { nome: 'SAINT KITTS E NEVIS', codigo: '3418' },
  { nome: 'SAINT LUCIA', codigo: '7150' },
  { nome: 'SAINT VINCENT E GRENADINES', codigo: '7053' },
  { nome: 'SAMOA', codigo: '6904' },
  { nome: 'SAMOA AMERICANA', codigo: '6912' },
  { nome: 'SAN MARINO', codigo: '6971' },
  { nome: 'SANTA HELENA', codigo: '7100' },
  { nome: 'SANTA SEDE (VATICANO)', codigo: '8486' },
  { nome: 'SAO BARTOLOMEU', codigo: '6939' },
  { nome: 'SAO MARTINHO (PARTE FRANCESA)', codigo: '6998' },
  { nome: 'SAO PEDRO E MIQUELON', codigo: '7005' },
  { nome: 'SAO TOME E PRINCIPE', codigo: '7207' },
  { nome: 'SENEGAL', codigo: '7283' },
  { nome: 'SERRA LEOA', codigo: '7356' },
  { nome: 'SERVIA', codigo: '7372' },
  { nome: 'SEYCHELLES', codigo: '7313' },
  { nome: 'SIRIA', codigo: '7445' },
  { nome: 'SOMALIA', codigo: '7488' },
  { nome: 'SRI LANKA', codigo: '7500' },
  { nome: 'SUAZILANDIA', codigo: '7542' },
  { nome: 'SUDAO', codigo: '7593' },
  { nome: 'SUDAO DO SUL', codigo: '7607' },
  { nome: 'SUECIA', codigo: '7640' },
  { nome: 'SUICA', codigo: '7674' },
  { nome: 'SURINAME', codigo: '7704' },
  { nome: 'TAILANDIA', codigo: '7763' },
  { nome: 'TAIWAN', codigo: '1619' },
  { nome: 'TANZANIA', codigo: '7801' },
  { nome: 'TERRITORIO BRITANICO DO OCEANO INDICO', codigo: '7820' },
  { nome: 'TIMOR LESTE', codigo: '7951' },
  { nome: 'TOGO', codigo: '8001' },
  { nome: 'TOKELAU', codigo: '8052' },
  { nome: 'TONGA', codigo: '8109' },
  { nome: 'TRINIDAD E TOBAGO', codigo: '8150' },
  { nome: 'TUNISIA', codigo: '8206' },
  { nome: 'TURCOMENISTAO', codigo: '8249' },
  { nome: 'TURQUIA', codigo: '8273' },
  { nome: 'TUVALU', codigo: '8281' },
  { nome: 'UCRANIA', codigo: '8311' },
  { nome: 'UGANDA', codigo: '8338' },
  { nome: 'URUGUAI', codigo: '8451' },
  { nome: 'UZBEQUISTAO', codigo: '8478' },
  { nome: 'VANUATU', codigo: '5517' },
  { nome: 'VENEZUELA', codigo: '8508' },
  { nome: 'VIETNA', codigo: '8583' },
  { nome: 'ZAMBIA', codigo: '8907' },
  { nome: 'ZIMBABUE', codigo: '6653' },
] as const;

